/**
 * Japan 2027 itinerary data
 * Edit this file to change dates, costs, or reminders.
 */

window.HOLIYAY_DATA = {
  trip: {
    title: "Japan 2027",
    destination: "Tokyo → Hakone → Kyoto → Osaka → Nara → Kanazawa → Tokyo",
    startDate: "2027-01-13",
    endDate: "2027-01-31",
    currency: "JPY",
    defaultRateToAUD: 97, // JPY per 1 AUD – update for current rate
    // Password to view the itinerary. Share this with your partner so you both use the same one (and see the same synced data).
    accessPassword: "japan2027",
    // Optional: shared sync so you both see the same updates. Create a free project at supabase.com, add a table (see README), then set:
    syncSupabaseUrl: "https://kxptmcvijnszpelydluq.supabase.co",
    syncSupabaseAnonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4cHRtY3Zpam5zenBlbHlkbHVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwOTI0MDksImV4cCI6MjA4ODY2ODQwOX0.PBBOKUAgwz3zeUXnitUAVFCAv8QYs7J96P4cVrzsnJQ",
  },

  /** Confirmed bookings – enter amount in one currency; the app shows the other using your exchange rate. */
  bookingsSoFar: [
    { label: "Hotel Sunroute Plaza Shinjuku", dates: "13 Jan – 18 Jan 2027", amount: 1268, currency: "AUD" },
    { label: "Shirayunoyado Yamadaya Hakone Gora", dates: "18 Jan – 19 Jan 2027", amount: 45900, currency: "JPY" },
  ],

  /** Tentative flights (Cathay Pacific via Hong Kong) */
  flights: {
    outbound: [
      { flight: "CX178", route: "Australia → Hong Kong" },
      { flight: "CX548", route: "Hong Kong → Tokyo Haneda" },
    ],
    return: [
      { flight: "CX521", route: "Tokyo Haneda → Hong Kong" },
      { flight: "CX105", route: "Hong Kong → Australia" },
    ],
    dealsNote: "Virgin Velocity: CommBank Awards points transfer to Velocity (1:0.4 standard, 1:0.5 premium cards). Check velocityfrequentflyer.com for partner redemptions. Cathay may be bookable with points via Velocity partners or compare cash fares.",
  },

  /** Things to book – paid/unpaid toggle and editable amount (AUD). Stored per device. */
  bookables: [
    { id: "flights", label: "Flights (Cathay via HK)", defaultAUD: 0 },
    { id: "hotel-shinjuku", label: "Hotel Sunroute Plaza Shinjuku", defaultAUD: 0 },
    { id: "ryokan-hakone", label: "Shirayunoyado Yamadaya Hakone Gora", defaultAUD: 0 },
    { id: "kyoto-accom", label: "Kyoto accommodation", defaultAUD: 0 },
    { id: "osaka-accom", label: "Osaka accommodation", defaultAUD: 0 },
    { id: "kanazawa-accom", label: "Kanazawa accommodation", defaultAUD: 0 },
    { id: "transport", label: "Transport (Hakone pass, IC, Shinkansen for two)", defaultAUD: 1134 },
    { id: "sumo", label: "January Grand Sumo tickets", defaultAUD: 0 },
    { id: "disney", label: "Tokyo DisneySea (e.g. 2× tickets)", defaultAUD: 450 },
    { id: "romancecar", label: "Romancecar Shinjuku → Hakone", defaultAUD: 0 },
    { id: "tea-ceremony", label: "Oboro Tea Ceremony (Kyoto)", defaultAUD: 0 },
    { id: "hakone-pass", label: "Hakone Free Pass", defaultAUD: 0 },
  ],

  reminders: [
    { id: "flights", label: "Flights to/from Japan", bookBy: "2026-09-30", notes: "3–4 months ahead for better prices" },
    { id: "hotel-shinjuku", label: "Hotel Sunroute Plaza Shinjuku", bookBy: "2026-10-15", notes: "Tokyo nights 1–6" },
    { id: "ryokan-hakone", label: "Shirayunoyado Yamadaya Hakone Gora", bookBy: "2026-10-15", notes: "Ryokan – book early" },
    { id: "kyoto-accom", label: "Kyoto accommodation", bookBy: "2026-10-31", notes: "Nights 8–11" },
    { id: "osaka-accom", label: "Osaka accommodation", bookBy: "2026-10-31", notes: "Nights 12–14" },
    { id: "kanazawa-accom", label: "Kanazawa accommodation", bookBy: "2026-11-15", notes: "Nights 15–17" },
    { id: "sumo", label: "January Grand Sumo tickets (Ryogoku)", bookBy: "2026-12-05", notes: "On sale ~1 month before" },
    { id: "disney", label: "Tokyo DisneySea tickets", bookBy: "2026-11-30", notes: "Can book up to 2 months ahead" },
    { id: "romancecar", label: "Romancecar Shinjuku → Hakone", bookBy: "2026-12-15", notes: "Reserve seats in advance" },
    { id: "tea-ceremony", label: "Oboro Tea Ceremony (Kyoto)", bookBy: "2026-12-20", notes: "Book 2–4 weeks ahead" },
    { id: "hakone-pass", label: "Hakone Free Pass", bookBy: "2027-01-01", notes: "Buy at Odawara or online before travel" },
  ],

  transportSummary: {
    label: "Transport (for two)",
    jpy: 110000,
    notes: "Hakone Free Pass, IC card, individual Shinkansen. JR Pass would cost nearly double.",
  },

  /** Estimated travel times between cities (for planning). Shown in itinerary and below. */
  travelTimes: [
    { route: "Tokyo → Hakone", duration: "~1h 30m", how: "Romancecar" },
    { route: "Odawara → Kyoto", duration: "~2h", how: "Shinkansen" },
    { route: "Kyoto → Osaka", duration: "~30 min", how: "JR Kyoto Line" },
    { route: "Osaka ↔ Nara", duration: "~45 min", how: "JR Yamatoji Line" },
    { route: "Osaka → Kanazawa", duration: "~2h 30m", how: "Thunderbird" },
    { route: "Kanazawa → Tokyo", duration: "~2h 30m", how: "Hokuriku Shinkansen" },
  ],

  /** Venue alternatives by category – same type & area. Addresses/hours from Google; verify before travel. */
  venueCategories: [
    {
      id: "soul_record_bars",
      label: "Soul / record bars",
      area: "Tokyo (Shinjuku, Shibuya, Shimokitazawa)",
      venues: [
        { id: "bar_soul_stream", name: "Bar Soul Stream", address: "FB Bldg 1F, 3-10-9 Shinjuku, Shinjuku-ku, Tokyo 160-0022", hours: "18:00–01:00 (last order 24:00). Closed Tue.", phone: "03-3356-9600", isDefault: true },
        { id: "record_bar_analog", name: "Record Bar Analog", address: "3F Yanagimitsu Bldg, 2-20-9 Dogenzaka, Shibuya-ku, Tokyo 150-0043", hours: "20:00–03:00", phone: "03-6416-1228", isDefault: false },
        { id: "little_soul_cafe", name: "Little Soul Cafe", address: "2F Taisei Bldg, 3-20-2 Kitazawa, Setagaya-ku, Tokyo 155-0031", hours: "19:00–02:00 daily", phone: "03-5454-9800", isDefault: false },
        { id: "record_bar_33rpm", name: "Record Bar 33 1/3 rpm", address: "Shibuya Five Bldg B1F, 1-6-2 Dogenzaka, Shibuya-ku, Tokyo", hours: "19:00–24:00 (last entry 23:00). Closed Sun.", phone: "03-3770-0199", isDefault: false },
        { id: "soul_bar_phillys", name: "Soul Bar PHILLY'S", address: "Check Google Maps for current address", hours: "Check Google for hours", phone: "", isDefault: false },
      ],
    },
    {
      id: "restaurants_tokyo",
      label: "Restaurants (Tokyo – Shinjuku/Shibuya)",
      area: "Near itinerary",
      venues: [
        { id: "torikatsu", name: "Torikatsu Chicken", address: "Dogenzaka, Shibuya (2F, back alley past Shibuya 109). Look for white noren.", hours: "Closed Sun. Check Google for current hours.", phone: "", isDefault: true },
        { id: "noeud_tokyo", name: "Noeud Tokyo", address: "B1F Hilcrest Hirakawacho, 2-5-7 Hirakawacho, Chiyoda-ku, Tokyo", hours: "Tue–Fri 18:00–22:30. Sat lunch 12:00–15:00, dinner 18:00–22:30. Closed Sun & Mon.", phone: "03-6910-0233", isDefault: false },
        { id: "noeud_alt", name: "Other Tokyo dinner options", address: "Search “restaurants Shinjuku” or “Shibuya dinner” on Google", hours: "Varies", phone: "", isDefault: false },
      ],
    },
    {
      id: "restaurants_kyoto",
      label: "Restaurants (Kyoto)",
      area: "Kawaramachi / Nishiki area",
      venues: [
        { id: "moon_and_back", name: "Moon and Back Ramen Bar", address: "585 Takamiya-cho, Nakagyo-ku, Kyoto 604-8056 (near Nishiki, ~4 min walk from Kawaramachi Stn)", hours: "Dinner 18:00–02:00. Lunch/Cafe 12:00–16:30. Weekend brunch 09:00–11:00.", phone: "075-744-0080", isDefault: true },
        { id: "chao_chao_sanjo", name: "Chao Chao Gyoza (Sanjo Kiyamachi)", address: "117 Ishiyacho, Nakagyo Ward, Kyoto 604-8002", hours: "Mon–Fri 16:00–22:30. Sat–Sun 14:00–22:30.", phone: "075-251-0056", isDefault: false },
        { id: "chao_chao_shijo", name: "Chao Chao Gyoza (Shijo Kawaramachi)", address: "312-1 Jumpucho, Kawaramachidori Shijo Sagaru, Shimogyo-ku, Kyoto 600-8021", hours: "Mon–Fri 16:00–23:00. Sat–Sun 14:00–23:00.", phone: "075-353-2626", isDefault: false },
        { id: "kyoto_alt", name: "Other Kyoto options", address: "Search “restaurants Kyoto Kawaramachi” on Google", hours: "Varies", phone: "", isDefault: false },
      ],
    },
    {
      id: "restaurants_kanazawa",
      label: "Restaurants (Kanazawa)",
      area: "Near Omicho Market",
      venues: [
        { id: "okina_sushi", name: "Okina Sushi", address: "2-1-5 Hikosomachi, Kanazawa, Ishikawa 920-0901", hours: "12:00–22:00 (irregular holidays)", phone: "076-231-2655", isDefault: true },
        { id: "kanazawa_alt", name: "Other Kanazawa options", address: "Search “Omicho Market restaurants” or “Higashi Chaya dining” on Google", hours: "Varies", phone: "", isDefault: false },
      ],
    },
  ],

  days: [
    {
      day: 1,
      date: "2027-01-13",
      title: "Tokyo arrival",
      location: "Tokyo",
      hotel: "Hotel Sunroute Plaza Shinjuku",
      morning: [],
      afternoon: [],
      evening: [
        { type: "Walk", text: "Shibuya Crossing" },
        { type: "Dinner", text: "Torikatsu Chicken", venueCategory: "restaurants_tokyo", venueId: "torikatsu" },
      ],
      night: [{ type: "Soul music bar", text: "Bar Soul Stream", venueCategory: "soul_record_bars", venueId: "bar_soul_stream" }],
      costJpy: null,
    },
    {
      day: 2,
      date: "2027-01-14",
      title: "Tokyo temples + records",
      location: "Tokyo",
      morning: [{ type: "Temple", text: "Senso-ji" }],
      afternoon: [
        { type: "Shrine", text: "Meiji Shrine" },
        { type: "Record stores", text: "Tower Records Shibuya, Disk Union Shibuya" },
      ],
      evening: [{ type: "Dinner", text: "Noeud Tokyo", venueCategory: "restaurants_tokyo", venueId: "noeud_tokyo" }],
      night: [{ type: "Vinyl bar", text: "Record Bar Analog", venueCategory: "soul_record_bars", venueId: "record_bar_analog" }],
      costJpy: null,
    },
    {
      day: 3,
      date: "2027-01-15",
      title: "Disney",
      location: "Tokyo",
      morning: [],
      afternoon: [{ type: "Park", text: "Tokyo DisneySea" }],
      evening: [],
      night: [],
      costJpy: 21800,
      costNote: "per person (estimate)",
    },
    {
      day: 4,
      date: "2027-01-16",
      title: "Sumo + market",
      location: "Tokyo",
      morning: [{ type: "Food market", text: "Tsukiji Outer Market" }],
      afternoon: [],
      evening: [
        { type: "Venue", text: "Ryogoku Kokugikan – January Grand Sumo Tournament" },
      ],
      night: [],
      costJpy: null,
    },
    {
      day: 5,
      date: "2027-01-17",
      title: "Music + thrift day",
      location: "Tokyo",
      morning: [
        { type: "Area", text: "Shimokitazawa" },
        { type: "Activities", text: "Record shops (e.g. Flash Disc Ranch) + thrift shopping" },
      ],
      afternoon: [
        { type: "Denim shopping", text: "Daikanyama – Momotaro Jeans, Pure Blue Japan, Evisu, Kapital" },
      ],
      evening: [],
      night: [{ type: "Soul bar", text: "Little Soul Cafe", venueCategory: "soul_record_bars", venueId: "little_soul_cafe" }],
      costJpy: null,
    },
    {
      day: 6,
      date: "2027-01-18",
      title: "Tokyo → Hakone",
      location: "Hakone",
      hotel: "Shirayunoyado Yamadaya Hakone Gora",
      morning: [],
      afternoon: [
        { type: "Train", text: "Romancecar Shinjuku → Hakone (Hakone Free Pass)", travelTime: "~1h 30m" },
      ],
      evening: [
        { type: "Hotel", text: "Private onsen soak + ryokan dinner/relax (early night to unwind after Tokyo pace)" },
      ],
      night: [],
      costJpy: null,
    },
    {
      day: 7,
      date: "2027-01-19",
      title: "Hakone chill & nature day",
      location: "Hakone",
      morning: [],
      afternoon: [
        { type: "Easy pace", text: "Hakone Ropeway to Owakudani (black eggs, views—Mt. Fuji often clearest in winter)" },
        { type: "Optional", text: "Lake Ashi stroll or short cruise, Hakone Shrine walk (serene paths)" },
      ],
      evening: [{ type: "Shinkansen", text: "Odawara → Kyoto (arrive relaxed)", travelTime: "~2h" }],
      night: [],
      costJpy: null,
      notes: "Skip rushing; focus on photos, hot drinks, fresh air. Alternative chill: onsen hopping (e.g. Hakone Yuryo outdoor baths) or ryokan lounge with views.",
    },
    {
      day: 8,
      date: "2027-01-20",
      title: "Kyoto arrival & easy start",
      location: "Kyoto",
      morning: [
        { type: "Temple", text: "Fushimi Inari Taisha (early to beat crowds; lower paths for photos or hike trails)" },
      ],
      afternoon: [],
      evening: [{ type: "Dinner", text: "Moon and Back Ramen Bar (warm comfort food)", venueCategory: "restaurants_kyoto", venueId: "moon_and_back" }],
      night: [],
      costJpy: null,
    },
    {
      day: 9,
      date: "2027-01-21",
      title: "Temple + Higashiyama",
      location: "Kyoto",
      morning: [{ type: "Temple", text: "Kiyomizu-dera" }],
      afternoon: [{ type: "Area", text: "Higashiyama stroll (quiet lanes, shops—keep it slow)" }],
      evening: [],
      night: [],
      costJpy: null,
    },
    {
      day: 10,
      date: "2027-01-22",
      title: "Food + culture",
      location: "Kyoto",
      morning: [{ type: "Market", text: "Nishiki Market (snack and wander)" }],
      afternoon: [{ type: "Tea ceremony", text: "Oboro Tea Ceremony" }],
      evening: [{ type: "Dinner", text: "Chao Chao Gyoza", venueCategory: "restaurants_kyoto", venueId: "chao_chao_sanjo" }],
      night: [],
      costJpy: null,
    },
    {
      day: 11,
      date: "2027-01-23",
      title: "Kyoto chill day (relaxation buffer)",
      location: "Kyoto",
      morning: [
        { type: "Relax", text: "Sleep in, cafe hopping or konbini breakfast in room" },
      ],
      afternoon: [],
      evening: [{ type: "Evening", text: "Low-key dinner nearby or back to hotel early" }],
      night: [],
      costJpy: null,
      notes: "Options: Arashiyama Bamboo Grove (peaceful winter quiet). Onsen/sento (e.g. Funaoka Onsen). Museum (Kyoto National Museum or crafts). Kamo River or Philosopher's Path. Optional: massage or hotel downtime with tea/hot chocolate.",
    },
    {
      day: 12,
      date: "2027-01-24",
      title: "Kyoto → Osaka",
      location: "Osaka",
      morning: [{ type: "Train", text: "JR Kyoto Line", travelTime: "~30 min" }],
      afternoon: [{ type: "Visit", text: "Osaka Castle" }],
      evening: [],
      night: [{ type: "Food", text: "Dotonbori (street eats, neon vibes—pace yourself)" }],
      costJpy: null,
    },
    {
      day: 13,
      date: "2027-01-25",
      title: "Osaka market",
      location: "Osaka",
      morning: [{ type: "Market", text: "Kuromon Ichiba Market (street food grazing)" }],
      afternoon: [],
      evening: [],
      night: [],
      costJpy: null,
    },
    {
      day: 14,
      date: "2027-01-26",
      title: "Nara day trip",
      location: "Nara",
      morning: [{ type: "Train", text: "JR Yamatoji Line", travelTime: "~45 min" }],
      afternoon: [
        { type: "Visit", text: "Nara Park + Todai-ji (deer feeding, temple—relaxed wandering)" },
      ],
      evening: [],
      night: [],
      costJpy: null,
    },
    {
      day: 15,
      date: "2027-01-27",
      title: "Osaka → Kanazawa",
      location: "Kanazawa",
      morning: [{ type: "Train", text: "Thunderbird Limited Express", travelTime: "~2h 30m" }],
      afternoon: [],
      evening: [{ type: "Dinner", text: "Okina Sushi", venueCategory: "restaurants_kanazawa", venueId: "okina_sushi" }],
      night: [],
      costJpy: null,
    },
    {
      day: 16,
      date: "2027-01-28",
      title: "Garden + geisha district",
      location: "Kanazawa",
      morning: [{ type: "Garden", text: "Kenrokuen Garden (winter beauty, snow possible—stroll slowly)" }],
      afternoon: [{ type: "District", text: "Higashi Chaya District (geisha area walk, tea houses)" }],
      evening: [],
      night: [],
      costJpy: null,
    },
    {
      day: 17,
      date: "2027-01-29",
      title: "Market + optional onsen",
      location: "Kanazawa",
      morning: [{ type: "Market", text: "Omicho Market (fresh seafood, casual eats)" }],
      afternoon: [
        { type: "Optional", text: "Yuwaku Onsen day trip (~30 min bus; tranquil hot springs—great winter relaxer)" },
      ],
      evening: [],
      night: [],
      costJpy: null,
    },
    {
      day: 18,
      date: "2027-01-30",
      title: "Kanazawa → Tokyo",
      location: "Tokyo",
      morning: [{ type: "Train", text: "Hokuriku Shinkansen", travelTime: "~2h 30m" }],
      afternoon: [
        { type: "Arrive", text: "Tokyo – light shopping or rest (hotel check-in if needed)" },
      ],
      evening: [],
      night: [],
      costJpy: null,
    },
    {
      day: 19,
      date: "2027-01-31",
      title: "Tokyo → flight home",
      location: "Tokyo",
      morning: [
        { type: "Market", text: "Tsukiji Outer Market" },
        { type: "Shopping", text: "Ginza, Shibuya" },
      ],
      afternoon: [],
      evening: [],
      night: [],
      costJpy: null,
    },
  ],
};
